version: "2"
linters:
  default: none
  enable:
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - promlinter
    - revive
    - staticcheck
    - unconvert
    - unused
  exclusions:
    generated: lax
    rules:
      - linters:
          - promlinter
        path: _test\.go
      - linters:
          - gosec
        text: 'G104:'
      - linters:
          - revive
        text: 'package-comments:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - k8s.io/kube-state-metrics
        - k8s.io/kube-state-metrics/v2
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
