name: govulncheck

on:
  schedule:
    # Run every Monday
    - cron: '0 0 * * 1'

env:
  GO_VERSION: "^1.24"

permissions:
  contents: read

jobs:
  ci-security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        name: Checkout code
      - name: Set up Go 1.x
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install govulncheck binary
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run security checks
        run: |
          govulncheck ./...
